<a href="https://colab.research.google.com/github/RofiqAulia/Machine-Learning/blob/main/Week1ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:

# Implementasi Normalisasi
def norm_data(data) :
  '''
  Fungsi ini digunakan untuk
  Melakukan normaliasasi data.

  Parameters::
    data(list):data yang akan dinormaliasaikan
  Retruns:
    data (list) : data yang sudah dinormaliasikan
  '''
  data_max = max(data)
  data_min = min(data)
  data_len = len(data)

  for i in range(0, data_len) :
    data[i] = (data[i]- data_min) / (data_max - data_min)
  return data

# Contoh penggunaan
data = [10, 11, 12, 14, 16]
n_data = norm_data(data) # melakukan normalisasi
print(n_data)
print('\n')

import numpy as np
from sklearn.preprocessing import MinMaxScaler

np.set_printoptions(precision=6) # bulatkan 4 angka koma
np.set_printoptions(suppress=True) # hilangkan nilai e


# Kita akan membentuk data
# Hal ini dikarenakan, sedikitnya-leran hanya menerima input
# Dalam bentuk n-dimensional array

data = [
    [100,0.10001],
    [50,0.05],
    [30,0.003]
]

#  Ubah ke bentuk array numpy n-dimensional array
data = np.array(data)
print("Data Asli")
print(data)

# Mendefinikan objek MinMaxScaler
scaler = MinMaxScaler()
# Transformasikan data
scaled = scaler.fit_transform(data)
print("Data Setelah dinormalisasi")
print(scaled)
print('\n')


# Implemenasi Standarisasi
import numpy as np
from sklearn.preprocessing import StandardScaler

np.set_printoptions(precision=6) # bulatkan 4 angka koma
np.set_printoptions(suppress=True) # hilangkan nilai e

# Kita akan membentuk data
# Hal ini dikarenakan scikitnya-learn hanya menerima input
# Dalam bentuk n-dimensional array

data = [
    [100,0.0001],
    [50,0.05],
    [30,0.003]
]

# Ubah ke bentuk numpy n-dimensional array
data = np.array(data)
print("Data Asli")
print(data)

# Mendefinisikan objek MinMaxScaler
scaler = StandardScaler()
# Transformasikan data
scaled = scaler.fit_transform(data)
print("Data Standarisasi")
print(scaled)
print('\n')

# 3. Implementasi Ordinal Encoding
from sklearn.preprocessing import OrdinalEncoder

# Inisialisasi obyek Encoder
oe = OrdinalEncoder()

# Definisikan data
# Dalam bentuk 2D

data = [
    ['Politeknik Negeri Malang'],
    ['Politeknik Elektronika Negeri Surabaya'],
    ['Politeknik Negeri jakarta'],
    ['Politeknik Negeri Semarang']
]

# Transformasikan data
transform_eo = oe.fit_transform(data)

print("Data Asli")
print(data)
print("Data Transformasi Ordinal Encoder")
print(transform_eo)
print('\n')

# 4. Implementasi One-Hot Encoding
from sklearn.preprocessing import OneHotEncoder

# Inisialisasi obyek Encoder
ohe = OneHotEncoder()

# Definisikan data
# Dalam bentuk 2D

data = [
    ['Politeknik Negeri Malang'],
    ['Politeknik Elektronika Negeri Surabaya'],
    ['Politeknik Negeri jakarta'],
    ['Politeknik Negeri Semarang']
]

# Transformasikan data
transform_eho = ohe.fit_transform(data)

print("Data Asli")
print(data)
print("Data Transformasi Ordinal Encoder")
print(transform_eho.toarray())
print('\n')

# 5. Implementasi Dummy Variable Encoding
from sklearn.preprocessing import OneHotEncoder

# Inisialisasi obyek Encoder
de = OneHotEncoder(drop='first')

# Definisikan data
# Dalam bentuk 2D

data = [
    ['Politeknik Negeri Malang'],
    ['Politeknik Elektronika Negeri Surabaya'],
    ['Politeknik Negeri jakarta'],
    ['Politeknik Negeri Semarang']
]

# Transformasikan data
transform_de = de.fit_transform(data)

print("Data Asli")
print(data)
print("Data Transformasi Ordinal Encoder")
print(transform_de.toarray())
print('\n')

# 6. Studi Kasus Ekstrasi Fitur dari Data Teks
from sklearn.feature_extraction.text import TfidfVectorizer

corpus = [
    'the house had a tiny little mouse',
    'the cat saw the mouse',
    'the mouse ran away from the house',
    'the cat finally ate the mouse',
    'the end of the mouse story'
]

# Inisiasi obyek TfdfVectorizer
vect = TfidfVectorizer(stop_words='english')

# Pembobotan TF-IDF
resp = vect.fit_transform(corpus)

# Cetak Hasil
print("Hasil TF-IDF")
print(resp)

# Cetak token stopword
print("hasil Token")
print(vect.get_feature_names_out())
print('\n')





[0.0, 0.16666666666666666, 0.3333333333333333, 0.6666666666666666, 1.0]


Data Asli
[[100.        0.10001]
 [ 50.        0.05   ]
 [ 30.        0.003  ]]
Data Setelah dinormalisasi
[[1.       1.      ]
 [0.285714 0.484486]
 [0.       0.      ]]


Data Asli
[[100.       0.0001]
 [ 50.       0.05  ]
 [ 30.       0.003 ]]
Data Standarisasi
[[ 1.358732 -0.76956 ]
 [-0.339683  1.412317]
 [-1.019049 -0.642757]]


Data Asli
[['Politeknik Negeri Malang'], ['Politeknik Elektronika Negeri Surabaya'], ['Politeknik Negeri jakarta'], ['Politeknik Negeri Semarang']]
Data Transformasi Ordinal Encoder
[[1.]
 [0.]
 [3.]
 [2.]]


Data Asli
[['Politeknik Negeri Malang'], ['Politeknik Elektronika Negeri Surabaya'], ['Politeknik Negeri jakarta'], ['Politeknik Negeri Semarang']]
Data Transformasi Ordinal Encoder
[[0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]]


Data Asli
[['Politeknik Negeri Malang'], ['Politeknik Elektronika Negeri Surabaya'], ['Politeknik Negeri jakarta'], ['Politeknik Negeri

In [15]:
from sklearn.feature_extraction.text import TfidfVectorizer

with open('corpus.txt', 'r') as file:
    corpus = file.readlines()

# Inisiasi obyek TfdfVectorizer
vect = TfidfVectorizer(stop_words='english')

# Pembobotan TF-IDF
resp = vect.fit_transform(corpus)

# Cetak Hasil
print("Hasil TF-IDF")
print(resp)

# Cetak token stopword
print("hasil Token")
print(vect.get_feature_names_out())
print('\n')

Hasil TF-IDF
  (0, 7)	0.2808823162882302
  (0, 6)	0.5894630806320427
  (0, 11)	0.5894630806320427
  (0, 5)	0.47557510189256375
  (1, 9)	0.7297183669435993
  (1, 2)	0.5887321837696324
  (1, 7)	0.3477147117091919
  (2, 1)	0.5894630806320427
  (2, 8)	0.5894630806320427
  (2, 7)	0.2808823162882302
  (2, 5)	0.47557510189256375
  (3, 0)	0.5894630806320427
  (3, 4)	0.5894630806320427
  (3, 2)	0.47557510189256375
  (3, 7)	0.2808823162882302
  (4, 10)	0.6700917930430479
  (4, 3)	0.6700917930430479
  (4, 7)	0.3193023297639811
hasil Token
['ate' 'away' 'cat' 'end' 'finally' 'house' 'little' 'mouse' 'ran' 'saw'
 'story' 'tiny']


